name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-cml@v1
    - env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Can use the default token for most functions
      run: |
        # Your ML workflow goes here
        pip install -r requirements.txt
        python train.py

        echo 'My first CML report' > report.md
        echo '![](./feature_importance.png)' >> report.md
        cml comment create --publish report.md

